name: Git Pull on Master Push
on:
  push:
    branches:
      - [master, main]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull latest changes
        run: git pull
