name: Checkout master branch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: GitHub Action for DigitalOcean - doctl
      #   uses: digitalocean/action-doctl@v2.3.0

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin master