name: Checkout master branch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull latest changes
        run: git pull origin master